data = {
    "temperatura": 0,
    "dias_febre": 0,
    "manchas_pele": 0,
    "dor_muscular": 0,
    "dor_articular": 0,
    "dor_articular_intensidade":0,
    "edema_articular": 0,
    "edema_articular_intensidade": 0,
    "conjuntivite": 0,
    "dor_cabeca": 0,
    "dor_cabeca_intensidade": 0,
    "coceira": 0,
    "hipertrofia_ganglionar": 0,
    "discrasia_hemorragica": 0,
    "acometimento_neurologico": 0,
    "porcentagem_dengue": 0,
    "porcentagem_zika": 0,
    "porcentagem_chiku": 0
}